version: '3.8'

services:
  db:
    container_name: event-go_db
    image: postgres
    restart: always
    ports:
      - 1100:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_event-go:/var/lib/postgresql/data
  pgadmin:
    container_name: event-go_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 1101:80
    depends_on:
      - db
volumes:
  db_data_event-go:
